### ISSUE TITLE
GDImageLoader.cmd doesnt work.

### ISSUE THREAD

**Issue by BlastkinS** [yellowww/GDImageLoader#1]
![image](https://user-images.githubusercontent.com/37024000/194940298-895c466e-54cf-4baf-b567-a78d9af6c4a1.png)
not a single image to gd program works i need heeeeeeelllppp

**Comment by DustyBerkley** [comment]
Do you have Node.js installed on your computer? 
Try running `node --version` in a command prompt. If it gives an error you need to download and install it from [here](https://nodejs.org/en/)

**Comment by randyr7** [comment]
> Do you have Node.js installed on your computer? Try running `node --version` in a command prompt. If it gives an error you need to download and install it from [here](https://nodejs.org/en/)

I installed it from there and the command worked, but I'm still having issues running GDImageLoader.cmd. I followed every step too.

**Comment by DustyBerkley** [comment]
Sorry for the extremely late response. I updated the repo to support crash logging. If you re-download the program from here and run it again (and let it crash), then send me the file at [logs/exit.json](https://github.com/yellowww/GDImageLoader/blob/main/logs/exit.json) it will greatly help me fix this issue.

**Comment by pizzapi2012** [comment]
its happening to me to!

**Comment by pizzapi2012** [comment]
fix it pls

**Comment by pizzapi2012** [comment]
i have more info why it is not working because ERR_DLOPEN_FAILED (i used pause at the end of the script)

**Comment by DustyBerkley** [comment]
It seems to be an issue with npm.
While I work on an actual patch here is a quick fix:
 1. delete the node_modules folder
 2. open a command prompt window in the location where you installed GDImageLoader
 3. run `npm install`
 4. Wait for it to finish loading and GDImageLoader.cmd should work

If for some reason you don't have npm installed (it should come packaged with node), you can install it with
 `curl -qL https://www.npmjs.com/install.sh | sh`

**Comment by pizzapi2012** [comment]
i fixed it just install canvas again! `npm i canvas` the dir in that the dir is in! @yellowww 

i,m 11 btw

**Comment by DustyBerkley** [comment]
There must be some hardware/os dependent version of canvas.

**Comment by pizzapi2012** [comment]
Can you close this ticket and put it in readme?

**Comment by pizzapi2012** [comment]
or add it to gdimageloader.cmd

**Comment by DustyBerkley** [comment]
Patched in [fixed canvas compatibility error](https://github.com/yellowww/GDImageLoader/commit/471d819920806069dbcb54dab1707a36e1ddc40d).
