### ISSUE TITLE
Just Errors. Tried everything, but it still doesnt work

### ISSUE THREAD

**Issue by NotActuallyRickAstley** [yellowww/GDImageLoader#3]
I am currently downloading this program on a somewhat fresh PC and dont have too much installed yet. I have looked at a bunch of logs, the solved issue with it not loading and tried installing visual studio and python (was an error in the Script). Im not too much into coding, but i feel like that im forgetting something trivial.
 Not entirely sure if this works but here is the log if i run it as admin
[2024-12-20T21_05_42_134Z-debug-0.log](https://github.com/user-attachments/files/18215373/2024-12-20T21_05_42_134Z-debug-0.log)

**Comment by DustyBerkley** [comment]
It seems to be an issue with an incorrect relative path in the `GDImageLoader.bat` file.
 
If this is the problem, you could easily get around it by manually installing the dependencies.
To do this:
* Navigate to the GDImageLoader directory in a command prompt and run `npm install`
* After that you should be able to successfully run the `GDImageLoader.bat` file and launch the application

Let me know if this fixes it. I will look into the incorrect path soon.

**Comment by NotActuallyRickAstley** [comment]
ummm...
cant even do this properly
here is the log for npm install:
[2024-12-20T21_40_52_810Z-debug-0.log](https://github.com/user-attachments/files/18215592/2024-12-20T21_40_52_810Z-debug-0.log)
Thanks for such a fast reply by the way

**Comment by DustyBerkley** [comment]
This is a completely different issue, not your fault. 

It is an issue with node-canvas, a dependency of GDImageLoader. It does not appear to be properly installing itself. Manually installing GTK onto your computer should fix this. To do this, follow the second step [here](https://github.com/Automattic/node-canvas/wiki/Installation%3A-Windows) under the install manually section.

Then rerun `npm install`.

I was unable to replicate the issue, but it seems to have happened to other people using the node-canvas library.

**Comment by NotActuallyRickAstley** [comment]
Thanks, it finally worked...
